### ISSUE TITLE
3.1时候可用 今天升级3.2设置好后 IDEA就不能启动了

### ISSUE THREAD

**Issue by qinkangdeid** [mrshawnho/ideaagent#3]
3.1时候可用 今天升级3.2设置好后 IDEA就不能启动了 在VM配置文件里 删掉-javaagent:命令 就可以启动IDEA
看启动日志报错如下：我打包的不对吗？
`log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalStateException: Failed to create cache dir
	at io.vertx.core.impl.FileResolver.setupCacheDir(FileResolver.java:299)
	at io.vertx.core.impl.FileResolver.<init>(FileResolver.java:92)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:185)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:144)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:140)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:34)
	at io.vertx.core.Vertx.vertx(Vertx.java:82)
	at shawnho.ideaagent.Server.run(Server.kt:14)
	at shawnho.ideaagent.ApplicationKt.premain(Application.kt:21)
	... 6 more
`

**Comment by mrshawnho** [comment]
@qinkangdeid 3.2测试没毛病哈 建议[这里](https://github.com/mrshawnho/ideaagent/releases)下载编译好的包 windows以管理员身份运行试试

**Comment by alexkie007** [comment]
请问一下在哪里删除这个参数  我的也启动不了了

**Comment by qinkangdeid** [comment]
@alexkie007  在你的配置目录下 ${user}\.IntelliJIdea2017.3\config\idea64.exe.vmoptions下  现在可以使用管理员身份运行就可以启动了

**Comment by qinkangdeid** [comment]
@mrshawnho  管理员身份运行就可以了  谢谢大神
