### ISSUE TITLE
启动报错（idea2017.3.1，MyBatis plugin3.53）

### ISSUE THREAD

**Issue by wangxin7** [mrshawnho/ideaagent#6]
本来MyBatis plugin3.42用的好好的，手贱点了升级。报错信息如下：
2018-02-27 11:27:46,463 [   6812]  ERROR - nsions.impl.ExtensionPointImpl - null 
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:96)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:246)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:191)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:102)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:50)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:292)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:254)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:469)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ExceptionInInitializerError
	at com.a.b.h.a.c.<init>(c.java:7)
	at com.a.b.h.a.c.<clinit>(c.java:1)
	at com.a.b.h.a.b.<init>(b.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:77)
	... 49 more
Caused by: java.lang.RuntimeException
	at com.a.b.h.b.b.<init>(b.java:3)
	at com.a.b.h.b.b.<clinit>(b.java:1)
	... 61 more
Caused by:

java.lang.ExceptionInInitializerError
	at com.a.b.h.a.c.<init>(c.java:7)
	at com.a.b.h.a.c.<clinit>(c.java:1)
	at com.a.b.h.a.b.<init>(b.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:77)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:246)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:191)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:102)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:50)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:292)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:254)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:469)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException
	at com.a.b.h.b.b.<init>(b.java:3)
	at com.a.b.h.b.b.<clinit>(b.java:1)
	... 61 more
2018-02-27 11:27:46,467 [   6816]  ERROR - nsions.impl.ExtensionPointImpl - IntelliJ IDEA 2017.3.1  Build #IU-173.3942.27 
2018-02-27 11:27:46,468 [   6817]  ERROR - nsions.impl.ExtensionPointImpl - JDK: 1.8.0_152-release 
2018-02-27 11:27:46,468 [   6817]  ERROR - nsions.impl.ExtensionPointImpl - VM: OpenJDK 64-Bit Server VM 
2018-02-27 11:27:46,468 [   6817]  ERROR - nsions.impl.ExtensionPointImpl - Vendor: JetBrains s.r.o 
2018-02-27 11:27:46,468 [   6817]  ERROR - nsions.impl.ExtensionPointImpl - OS: Windows 7 
2018-02-27 11:27:47,071 [   7420]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=0.0; restored: fontSize=12, fontScale=1.0 
2018-02-27 11:27:48,138 [   8487]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2018-02-27 11:27:48,750 [   9099]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.OptionsTopHitProvider$Activity@774d648b 
2018-02-27 11:27:49,147 [   9496]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2018-02-27 11:27:49,236 [   9585]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2018-02-27 11:27:49,879 [  10228]  ERROR - nsions.impl.ExtensionPointImpl - null

**Comment by FreeStyleNight** [comment]
新版本估计改了认证机制了吧，同样报错，希望作者有余力的话可以更新一下哟~谢谢啦 @mrshawnho

**Comment by zlsq** [comment]
同

**Comment by Summerslyb** [comment]
我看了下...DeleteByPrimaryKeyElementGenerator里面已经没有相关代码了
官网也已经下不到3.42版本的插件了...这个的反破解真变态

**Comment by mrshawnho** [comment]
谷歌搜一下应该能下到3.42的插件，周末抽时间看下3.53：）

**Comment by FreeStyleNight** [comment]
@mrshawnho 非常感谢 👍

**Comment by SimpleExpress** [comment]
@mrshawnho 现在安装官方3.53版本一直报这个错，完全卸载重装也没法解决，不知道是什么原因，有没有什么建议，谢谢。

![image](https://user-images.githubusercontent.com/1047330/36846952-9fcb6aae-1d97-11e8-9c90-ab502d9c6882.png)

**Comment by mrshawnho** [comment]
v1.11 已更新

**Comment by caochuansong** [comment]
请问如何使用呢，具体步骤是如何

**Comment by caochuansong** [comment]
去掉vm里面的agent配置，直接安装ideaagent-plugin-1.11.jar吗？
ideaagent-agent-1.11.jar有什么作用呢?

**Comment by mrshawnho** [comment]
@caochuansong 请下载zip包安装

**Comment by Xzk940727** [comment]
![image](https://user-images.githubusercontent.com/21021062/37137876-c18d4df6-22e2-11e8-97e6-0a55b1946049.png)
我也是出现这个问题，是验证失败了么？

**Comment by FreeStyleNight** [comment]
@Xzk940727 你直接下载作者在release中放 ideaagent-1.11.zip 这个 zip 包，然后不要解压，直接安装这个 zip 包，应该可以的，我用着没有问题

**Comment by mrshawnho** [comment]
官方封了国内大部分IP导致无法使用 稍安勿躁：）

2018-03-08 15:18 GMT+08:00 CodeBugs <notifications@github.com>:

**Comment by Xzk940727** [comment]
@mrshawnho 你好 这个如果说不开启 就没办法用是么
